version: "3.9"

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
  app:
    build: .
    environment:
      DB_URL: ${DB_URL}
      WS_SERVER_URL: ${WS_SERVER_URL}
      WS_CAMERA_URL: ${WS_CAMERA_URL}
      WS_CARD_URL: ${WS_CARD_URL}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      RECIPIENT_EMAIL: ${RECIPIENT_EMAIL}
    depends_on:
      - db
    ports:
      - "5000:5000"

